"""
SPDC simulation.

This module provides :class:`~photonpairlab.spdc.simulation.SPDC_Simulation`, which computes
the joint spectral amplitude (JSA) and joint spectral intensity (JSI) of photon pairs
generated by spontaneous parametric down-conversion (SPDC) in a nonlinear crystal.

The simulation evaluates:
- a pump spectral envelope on a wavelength grid,
- a phase-matching function via a longitudinal integral over the poling pattern,
- the resulting joint spectral amplitude (complex) and intensity.

Notes
-----
This module is intended to be documented with Sphinx using ``autodoc`` + ``napoleon``.
Docstrings follow NumPy style.
"""

import numpy as np
#from photonpairlab.spdc.spectral_analyser import SpectralAnalyzer
from photonpairlab.spdc.spdc_results import SPDCResults
from photonpairlab.crystal import Crystal
from photonpairlab.laser import BaseLaser
from photonpairlab.laser.utils_laser import bandwidth_wavelength_to_angular_bandwidth

from photonpairlab.spdc.spdc_config import SPDCGridConfig, SPDCCenterConfig, SPDCRunConfig, build_wavelength_axes

from photonpairlab.constants import C_VAC

class SPDC_Simulation:
    """
    Simulate spontaneous parametric down-conversion (SPDC) for a crystal and pump laser.

    The simulation is configured by a crystal (including its poling pattern) and a pump laser.
    A wavelength grid is constructed (either symmetric about the center wavelengths via
    ``dev_nm`` or from explicit signal/idler wavelength limits). The pump envelope and
    phase-matching function are evaluated on this grid to produce the joint spectral
    amplitude and intensity.

    Parameters
    ----------
    crystal : photonpairlab.crystal.Crystal
        Crystal instance. A poling pattern must be generated (``crystal.poling_pattern``)
        before running the simulation.
    laser : photonpairlab.laser.BaseLaser
        Pump laser model providing the pump wavelength and spectral bandwidth.
    wavelength_signal : float, optional
        Signal center wavelength (m) used to compute the center phase mismatch.
        If ``None``, defaults to ``2 * laser.wavelength_pump`` (degenerate SPDC).
    wavelength_idler : float, optional
        Idler center wavelength (m) used to compute the center phase mismatch.
        If ``None``, defaults to ``2 * laser.wavelength_pump`` (degenerate SPDC).
    wavelength_signal_range : list[float | None], optional
        Legacy interface for specifying the signal wavelength range as ``[start, end]`` (m).
        If both values are ``None``, the range is taken from ``grid``.
        Prefer using ``grid``.
    wavelength_idler_range : list[float | None], optional
        Legacy interface for specifying the idler wavelength range as ``[start, end]`` (m).
        If both values are ``None``, the range is taken from ``grid``.
        Prefer using ``grid``.
    grid : photonpairlab.spdc.spdc_config.SPDCGridConfig, optional
        Wavelength grid configuration. If ``None``, uses the default
        :class:`~photonpairlab.spdc.spdc_config.SPDCGridConfig`.

    Attributes
    ----------
    crystal : photonpairlab.crystal.Crystal
        Crystal instance used for the simulation.
    laser : photonpairlab.laser.BaseLaser
        Pump laser instance.
    wavelength_signal : float
        Signal center wavelength (m) used for phase-mismatch calculations.
    wavelength_idler : float
        Idler center wavelength (m) used for phase-mismatch calculations.
    grid : photonpairlab.spdc.spdc_config.SPDCGridConfig
        Grid configuration used to build wavelength axes in :meth:`run`.

    Raises
    ------
    ValueError
        If the crystal poling pattern is missing when initializing parameters.

    See Also
    --------
    photonpairlab.spdc.spdc_config.SPDCGridConfig
        Grid configuration (steps, dev_nm, and/or explicit wavelength ranges).
    photonpairlab.spdc.spdc_results.SPDCResults
        Container for simulation outputs (JSA/JSI and wavelength axes).
    """
    def __init__(
            self, crystal: Crystal, laser: BaseLaser,
            wavelength_signal: float | None=None, wavelength_idler : float | None=None,
            wavelength_signal_range: list[float | None] | None = None,
            wavelength_idler_range: list[float | None] | None = None,
            grid: SPDCGridConfig | None = None,
                 ):

        # Initialize the SPDC simulation with a crystal and laser object.
        self.crystal = crystal
        self.laser = laser
        if wavelength_signal is None:
            self.wavelength_signal = laser.wavelength_pump * 2  # Default to twice the pump wavelength if not specified
        else:
            self.wavelength_signal = wavelength_signal
        if wavelength_idler is None:
            self.wavelength_idler = laser.wavelength_pump * 2  # Default to twice the pump wavelength if not specified
        else:
            self.wavelength_idler = wavelength_idler

        wavelength_signal_range = wavelength_signal_range or [None, None]
        wavelength_idler_range = wavelength_idler_range or [None, None]

        if grid is not None:
            self.grid = grid
        elif wavelength_signal_range[0] is not None and wavelength_idler_range[0] is not None:
            # Legacy interface: build the grid from the explicit signal/idler ranges.
            self.grid = SPDCGridConfig(
                signal_range=(wavelength_signal_range[0], wavelength_signal_range[1]),
                idler_range=(wavelength_idler_range[0], wavelength_idler_range[1]),
            )
        else:
            self.grid = SPDCGridConfig()

        # Initialize other parameters
        self.initialize_parameters()
    
    def initialize_parameters(self):
        """
        Precompute and cache center-dependent simulation parameters.

        This method computes and stores:
        - the phase mismatch at the center wavelengths (via ``crystal.compute_phase_mismatch``),
        - the center angular frequencies for pump/signal/idler,
        - the pump angular bandwidth,
        - the effective nonlinear coupling profile (from the poling pattern) and the
          longitudinal coordinate for integration.

        Raises
        ------
        ValueError
            If ``crystal.poling_pattern`` is ``None`` (poling not generated).
        """
        
        #_, (N_pump, N_signal, N_idler), self.DeltaK_0 = self.crystal.compute_phase_mismatch(self.laser, self.wavelength_signal, self.wavelength_idler, T=self.crystal.T)
        self.pm_result = self.crystal.compute_phase_mismatch(self.laser, self.wavelength_signal, self.wavelength_idler, T=self.crystal.T)
        self.DeltaK_0 = self.pm_result.delta_k0
        # Center angular frequencies
        self.omega_pump = 2 * np.pi * C_VAC / self.laser.wavelength_pump
        self.omega_signal = 2 * np.pi * C_VAC / self.wavelength_signal
        self.omega_idler = 2 * np.pi * C_VAC / self.wavelength_idler

        # Bandwidth
        self.angular_bandwidth = bandwidth_wavelength_to_angular_bandwidth(self.laser.bandwidth_wavelength, self.laser.wavelength_pump)
        
        # xi_eff and z for simulation
        # xi_eff[k] must correspond to the same physical position as z[k]; the poling
        # pattern and z are generated together in matching order, so no reversal here
        # (reversing one but not the other silently conjugates the phase-matching
        # function's phase, which only matters once JSA carries phase information).
        pp = self.crystal.poling_pattern
        if pp is None:
            raise ValueError("Poling pattern is not generated in the crystal.")
        self.xi_eff = np.asarray(pp, dtype=np.float64)
        self.z = self.crystal.z
    
    def phase_matching_function(self, DeltaK):
        """
        Evaluate the phase-matching function on a (idler, signal) grid.

        The phase-matching function is computed as a longitudinal integral over the crystal:

        .. math::

           \\Phi(\\Delta k) = \\int \\xi_\\mathrm{eff}(z) e^{-i \\Delta k z} \\, dz

        where :math:`\\xi_\\mathrm{eff}(z)` encodes the effective nonlinear coupling
        (including the poling pattern).

        Parameters
        ----------
        DeltaK : ndarray
            Total phase mismatch array of shape ``(N_idler, N_signal)`` in rad/m.

        Returns
        -------
        ndarray
            Complex phase-matching function evaluated on the grid with shape
            ``(N_idler, N_signal)``.

        Notes
        -----
        This implementation uses the trapezoidal rule for numerical integration.
        """
        if self.z is None:
            raise ValueError("self.z must not be None")
        y = self.xi_eff[:, None, None] * np.exp(-1j * DeltaK[None, :, :] * self.z[:, None, None])
        return np.trapezoid(y, self.z, axis=0)
    
    def pump_pulse_envelope(self, signal_wavelengths: np.ndarray, idler_wavelengths: np.ndarray) -> np.ndarray:
        """
        Evaluate the (Gaussian) pump spectral envelope on a wavelength grid.

        The pump envelope is evaluated in angular-frequency space as a function of the
        signal and idler angular frequencies, using the constraint :math:`\\omega_s + \\omega_i`
        relative to the pump center frequency.

        Parameters
        ----------
        signal_wavelengths : ndarray
            Signal wavelength axis of shape ``(N_signal,)`` in meters.
        idler_wavelengths : ndarray
            Idler wavelength axis of shape ``(N_idler,)`` in meters.

        Returns
        -------
        ndarray
            Pump envelope on the 2D grid with shape ``(N_idler, N_signal)``.
        """
        fs = 2 * np.pi * C_VAC / signal_wavelengths[None, :]  # (1, Ns)
        fi = 2 * np.pi * C_VAC / idler_wavelengths[:, None]   # (Ni, 1)
        return np.exp(-((fi + fs - self.omega_pump) ** 2) / (2 * self.angular_bandwidth ** 2))
    
    def run(self) -> SPDCResults:
        """
        Run the SPDC simulation.

        This method:
        1. Builds wavelength axes from :attr:`grid` (via :func:`~photonpairlab.spdc.spdc_config.build_wavelength_axes`).
        2. Computes phase mismatch on the wavelength grid.
        3. Evaluates the pump envelope and phase-matching function.
        4. Forms the joint spectral amplitude (JSA) and joint spectral intensity (JSI).
        5. Returns an :class:`~photonpairlab.spdc.spdc_results.SPDCResults` instance.

        Returns
        -------
        SPDCResults
            Simulation results containing the pump envelope, phase-matching magnitude,
            joint spectral amplitude/intensity, and the signal/idler wavelength axes.

        Notes
        -----
        ``JSA`` is the complex joint spectral amplitude (phase included). ``JSI`` is
        the corresponding intensity, ``np.abs(JSA) ** 2``. Downstream interference
        calculations (Schmidt decomposition, HOM) require the complex ``JSA``.
        """
        cfg = SPDCRunConfig(
            center=SPDCCenterConfig(
                wavelength_signal=self.wavelength_signal,
                wavelength_idler=self.wavelength_idler,
            ),
            grid=self.grid,
        )

        signal_wavelengths, idler_wavelengths, wl_s0, wl_i0 = build_wavelength_axes(
            self.laser.wavelength_pump, cfg
        )

        # Compute delta_k on the grid
        DeltaK_1 = self.pm_result.compute_delta_k1(
            signal_wavelengths, idler_wavelengths, self.omega_signal, self.omega_idler
        )
        DeltaK = self.DeltaK_0 + DeltaK_1

        # Compute pump envelope and phase matching function
        PPE = self.pump_pulse_envelope(signal_wavelengths, idler_wavelengths)
        PMF = self.phase_matching_function(DeltaK)
        Amp = PPE * PMF


        return SPDCResults(
            Pump=PPE,
            Phase=np.abs(PMF),
            JSI=np.abs(Amp) ** 2,
            JSA=Amp,
            SchmidtCoefficients=None,
            Purity=None,
            K=None,
            SignalWavelengths=signal_wavelengths,
            IdlerWavelengths=idler_wavelengths,
            dev=cfg.grid.dev_nm,
            c=C_VAC,
        )