import numpy as np
from scipy.optimize import curve_fit, least_squares
from scipy.interpolate import interp1d
from inspect import signature

from photonpairlab.spdc.utils import *

class HOMAnalyzer:
    def __init__(self, *results):
        """
        Initializes the HOMAnalyzer class.

        Args:
            *results: One or more results dictionaries generated by simulation.py.
        """
        self.results_list = list(results)

    def get_reduced_density_matrix(self, mode="signal", results_index=0):
        """
        Computes the reduced density matrix from the Joint Spectral Amplitude (JSA) data.

        Args:
            mode (str): The mode to compute ("signal" or "idler").
            results_index (int): The index of the results object to use.

        Returns:
            tuple: The reduced density matrix and the interpolated JSA.
        """
        if results_index >= len(self.results_list):
            raise IndexError(f"Invalid results_index: {results_index}. Only {len(self.results_list)} results available.")

        results = self.results_list[results_index]
        JSA = results["JSA"]

        if mode == "signal":
            rho = JSA @ JSA.T.conj()
        elif mode == "idler":
            rho = JSA.T @ JSA.conj()
        else:
            raise ValueError(f"Invalid mode: {mode}. Choose 'signal' or 'idler'.")

        rho /= np.trace(rho)  # Normalize trace to 1
        return rho, JSA
    
    def compute_two_mode_HOM(self, mode1="signal", mode2="signal"):
        """
        Computes the two-mode HOM interference visibility.

        Returns:
            numpy.ndarray: The rescaled cross-correlation probabilities.
        """
        if len(self.results_list) < 2:
            raise ValueError("At least two results are required to compute two-mode HOM interference.")

        rho1, padded_jsa = self.get_reduced_density_matrix(mode=mode1, results_index=0)
        rho2, padded_jsa = self.get_reduced_density_matrix(mode=mode2, results_index=1)

        # Compute purity and visibility for both modes
        _, visibility1 = compute_purity_and_visibility(rho1)
        _, visibility2 = compute_purity_and_visibility(rho2)

        """
        Convert the reduced density matrices to the time domain using FFT.
        This is done by applying a 2D Fourier transform to the density matrices.
        The `fftshift` function is used to center the zero frequency component.
        Args:
            rho1 (numpy.ndarray): Reduced density matrix for mode 1.
            rho2 (numpy.ndarray): Reduced density matrix for mode 2.
        Returns:
            tuple: Temporal density matrices for mode 1 and mode 2.
        """
        rho1_temporal = convert_to_time_domain(rho1)
        rho2_temporal = convert_to_time_domain(rho2)

        # Compute cross-correlation probabilities
        P_tau_cross, t_values = compute_cross_correlation(rho1_temporal, rho2_temporal)
        # Rescale probabilities
        P_tau_rescaled_cross = rescale_probabilities(P_tau_cross, visibility1)
        
        results1 = self.results_list[0]
        results2 = self.results_list[1]

        # Check if signal wavelengths match
        try:
            if not np.array_equal(results1["SignalWavelengths"], results2["SignalWavelengths"]):
                raise ValueError("Signal wavelengths for results1 and results2 do not match.")
        except KeyError as e:
            raise KeyError(f"Missing key in results: {e}")

        # Check if idler wavelengths match
        try:
            if not np.array_equal(results1["IdlerWavelengths"], results2["IdlerWavelengths"]):
                raise ValueError("Idler wavelengths for results1 and results2 do not match.")
        except KeyError as e:
            raise KeyError(f"Missing key in results: {e}")

        if mode1 == mode2 == "signal":
            """
            Handle the case where both modes are signal.
            """
            wavelengths_1 = np.array(results1["SignalWavelengths"])
            wavelengths_2 = np.array(results2["SignalWavelengths"])

            frequencies_1 = np.sort(results1["c"] / wavelengths_1)
            frequencies_2 = np.sort(results2["c"] / wavelengths_2)
            delta_f_1 = (frequencies_1[-1] - frequencies_1[0]) / (len(frequencies_1) - 1)
            delta_f_2 = (frequencies_2[-1] - frequencies_2[0]) / (len(frequencies_2) - 1)
            delta_f_avg = 0.5 * (delta_f_1 + delta_f_2)
        elif mode1 == mode2 == "idler":
            """
            Handle the case where both modes are idler.
            """
            wavelengths_1 = np.array(results1["IdlerWavelengths"])
            wavelengths_2 = np.array(results2["IdlerWavelengths"])

            frequencies_1 = np.sort(results1["c"] / wavelengths_1)
            frequencies_2 = np.sort(results2["c"] / wavelengths_2)
            delta_f_1 = (frequencies_1[-1] - frequencies_1[0]) / (len(frequencies_1) - 1)
            delta_f_2 = (frequencies_2[-1] - frequencies_2[0]) / (len(frequencies_2) - 1)
            delta_f_avg = 0.5 * (delta_f_1 + delta_f_2)
        else:
            """
            Handle cross-mode cases: signal-idler or idler-signal.
            """
            if mode1 == "signal" and mode2 == "idler":
                wavelengths_1 = np.array(results1["SignalWavelengths"])
                wavelengths_2 = np.array(results2["IdlerWavelengths"])
            elif mode1 == "idler" and mode2 == "signal":
                wavelengths_1 = np.array(results1["IdlerWavelengths"])
                wavelengths_2 = np.array(results2["SignalWavelengths"])
            else:
                raise ValueError(f"Invalid modes: {mode1}, {mode2}. Choose 'signal' or 'idler'.")
            # Calculate frequencies and average delta_f
            frequencies_1 = np.sort(results1["c"] / wavelengths_1)
            frequencies_2 = np.sort(results2["c"] / wavelengths_2)
            delta_f_1 = (frequencies_1[-1] - frequencies_1[0]) / (len(frequencies_1) - 1)
            delta_f_2 = (frequencies_2[-1] - frequencies_2[0]) / (len(frequencies_2) - 1)
            delta_f_avg = np.sqrt(delta_f_1 * delta_f_2)
    
        # Use number of padded bins
        N_freq = padded_jsa.shape[0]

        # Compute time axis in femtoseconds
        time_bin_width = 1 / (N_freq * delta_f_avg)     # in seconds
        time_axis_fs = t_values * time_bin_width * 1e15  # in fs
        
        # Return results as a dictionary
        return {
            "P_tau_rescaled_cross": P_tau_rescaled_cross,
            "time_axis": time_axis_fs,
            "visibility1": visibility1,
            "visibility2": visibility2,
        }
